<div class="quick-order-popup" id="quick-order-popup">
    <form id="qoform" name="myform" action="<?= $block->getUrl('quickorder/save') ?>" method="post" data-mage-init='{"validation":{},"Roma_QuickOrder/js/quickorder":{}}'>
        <fieldset class="fieldset">
            <div class="field name required">
                <label class="label"><span>Name</span></label>
                <div class="control">
                    <input data-validate='{"required":true}' name="name" value="" class="input-text" type="text"/>
                </div>
            </div>
            <div class="field name required">
                <label class="label"><span>Phone</span></label>
                <div class="control">
                    <input data-validate='{"required":true ,
                                              "validate-digits":true ,
                                              "minlength":10 }'
                           name="phone" value="" class="input-text" type="text"/>
                </div>
            </div>
            <div>
                <label class="label"><span>E-mail</span></label>
                <div class="control">
                    <input data-validate='{"email2":true}' name="email" value="" type="text" class="input-text"/>
                </div>
            </div>
            <input id="sku-field" type="hidden" name="sku" value="<?php echo $sku ?? ''; ?>">
            <input id='quick-order-submit' type="submit" class="action primary" value="Send">
        </fieldset>
    </form>
</div>