<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= /* @escapeNotVerified */
            __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */
    $viewMode ?> products-<?= /* @escapeNotVerified */
    $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <li class="item product product-item">
                    <div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */
                    $viewMode ?>">
                        <?php
                        $productImage = $block->getImage($_product, $imageDisplayArea);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image ?>
                        <a href="<?= /* @escapeNotVerified */
                        $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?= $productImage->toHtml() ?>
                        </a>
                        <div class="product details product-item-details">
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?= /* @escapeNotVerified */
                                   $_product->getProductUrl() ?>">
                                    <?= /* @escapeNotVerified */
                                    $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </strong>
                            <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                            <?= /* @escapeNotVerified */
                            $block->getProductPrice($_product) ?>
                            <?= $block->getProductDetailsHtml($_product) ?>

                            <div class="product-item-inner">
                                <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                    <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                        <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form"
                                                  data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                                  action="<?= /* @NoEscape */
                                                  $postParams['action'] ?>" method="post">
                                                <input type="hidden" name="product" value="<?= /* @escapeNotVerified */
                                                $postParams['data']['product'] ?>">
                                                <input type="hidden" name="<?= /* @escapeNotVerified */
                                                Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */
                                                $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                <?= $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                        class="action tocart primary"
                                                        data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>">
                                                    <span><?= /* @escapeNotVerified */
                                                        __('Add to Cart') ?></span>
                                                </button>

                                                <button type="submit"
                                                        title="<?= $block->escapeHtml(__('QuickOrder')) ?>"
                                                        class="action primary qo">
                                                    <span><?= /* @escapeNotVerified */
                                                        __('QuickOrder') ?></span>
                                                </button>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_product->isAvailable()): ?>
                                                <div class="stock available"><span><?= /* @escapeNotVerified */
                                                        __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?= /* @escapeNotVerified */
                                                        __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                    <div data-role="add-to-links"
                                         class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                        <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                            <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <?php if ($showDescription): ?>
                                    <div class="product description product-item-description">
                                        <?= /* @escapeNotVerified */
                                        $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                        <a href="<?= /* @escapeNotVerified */
                                        $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */
                                        $_productNameStripped ?>"
                                           class="action more"><?= /* @escapeNotVerified */
                                            __('Learn More') ?></a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */
            $_product->getSku() ?>"
                }
            }
        }
        </script>
<div class="quick-order-popup" id="quick-order-popup">
    <form></form>
    <form id="qoform" name="myform" action="/quickorder" method="post" data-mage-init='{"validation":{}}'>
        <fieldset class="fieldset">
            <div class="field name required">
                <label class="label"><span>Name</span></label>
                <div class="control">
                    <input data-validate='{"required":true}' name="name" value="" class="input-text" type="text"/>
                </div>
            </div>
            <div class="field name required">
                <label class="label"><span>Phone</span></label>
                <div class="control">
                    <input data-validate='{"required":true ,
                                              "validate-digits":true ,
                                              "minlength":10 }'
                           name="phone" value="" class="input-text" type="text"/>
                </div>
            </div>
            <div>
                <label class="label"><span>E-mail</span></label>
                <div class="control">
                    <input data-validate='{"email2":true}' name="email" value="" type="text" class="input-text"/>
                </div>
            </div>
            <input type="text" name="sku" value="<?php echo $block->escapeHtml($_product->getSku()) ?? '';?>">
        </fieldset>
    </form>
</div>

<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/modal'
    ], function ($, modal) {
        var options = {
            type: 'popup',
            responsive: true,
            innerScroll: true,
            title: '<?php echo __('Fill in the fields, please!'); ?>',
            buttons: [{
                text: $.mage.__('Send'),
                class: 'action tocart primary',
                attr: {},
                click: function submitform()
                {
                    $('#qoform').submit();
                }
            }]
        };

        var popup = modal(options, $('#quick-order-popup'));

        $('.qo').on('click', function () {
            $('#quick-order-popup').modal('openModal');
            return false;
        });
    });
</script>

















































































        </script>
    <?php endif; ?>
<?php endif; ?>
