<?php
$sku = $block->getProduct()->getSku();
?>
<style>
    .quick-order-popup {
        display: none;
    }
</style>
<div class="quick-order">
    <button type="submit" title="QuickOrder" class="action tocart primary">
        <span>Quick Order</span>
    </button>
</div>
<div class="quick-order-popup" id="quick-order-popup">
    <form action="" method="post" data-mage-init='{"validation":{}}'>
        <fieldset class="fieldset">
            <div class="field name required">
                <label class="label"><span>Name</span></label>
                <div class="control">
                    <input data-validate='{"required":true}' name="name" value="" class="input-text" type="text"/>
                </div>
            </div>
            <div class="field name required">
                <label class="label"><span>Phone</span></label>
                <div class="control">
                    <input data-validate='{"required":true ,
                                              "validate-digits":true ,
                                              "minlength":10 }'
                           name="phone" value="" class="input-text" type="text"/>
                </div>
            </div>
            <div>
                <label class="label"><span>E-mail</span></label>
                <div class="control">
                    <input data-validate='{"email2":true}' name="email" value="" type="text" class="input-text"/>
                </div>
            </div>
            <input type="text" name="sku" value="<?php echo $sku ?? '';?>">
            <input style="width: 76.8px; height: 32px; margin-top: 25px; position: absolute; right: 30px; border-radius: 3px"
                   class="action tocart primary" type="submit" value="Send">
        </fieldset>
    </form>
</div>

<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/modal'
    ], function ($, modal) {

        var options = {
            type: 'popup',
            responsive: true,
            innerScroll: true,
            title: '<?php echo __('Fill in the fields, please!'); ?>',
            buttons: [{
                text: $.mage.__('Cancel'),
                class: 'action tocart primary',
                attr: {},
                action: 'action.php',
                click: function (event) {
                    this.closeModal(event);
                }
            },
                {
                    text: $.mage.__('Confirm'),
                    class: 'action tocart primary',
                    attr: {},
                    click: function (event) {
                        this.closeModal(event);
                    }
                }]
        };
        var slide = modal(options, $('#quick-order-popup'));

        $('.quick-order button').on('click', function () {

            $('#quick-order-popup').modal('openModal');
            return false;
        });
    });
</script>